module Hilary
	TWEETS = [
		"...in the Hillary Clinton Campaign where she deleted 33,000 Emails, got $145,000,000 while Secretary of State, paid McCabes wife $700,000 (and got off the FBI hook along with Terry M) and so much more. Republicans and real Americans should start getting tough on this Scam.",
		"Things are really getting ridiculous. The Failing and Crooked (but not as Crooked as Hillary Clinton) @nytimes has done a long & boring story indicating that the World’s most expensive Witch Hunt has found nothing on Russia & me so now they are looking at the rest of the World!",
		"(under FBI investigation that they killed) gave to McCabe’s wife in her run for office? Then dropped case on Clinton!",
		"NEW BOOK - A MUST READ! “The Russia Hoax - The Illicit Scheme to Clear Hillary Clinton and Frame Donald Trump” by the brilliant Fox News Legal Analyst Gregg Jarrett. A sad chapter for law enforcement. A rigged system!",
		"Just Out: House Intelligence Committee Report released. “No evidence” that the Trump Campaign “colluded, coordinated or conspired with Russia.” Clinton Campaign paid for Opposition Research obtained from Russia- Wow! A total Witch Hunt! MUST END NOW!",
		"“GOP Lawmakers asking Sessions to Investigate Comey and Hillary Clinton.” @FoxNews Good luck with that request!",
		"James Comey’s Memos are Classified, I did not Declassify them. They belong to our Government! Therefore, he broke the law! Additionally, he totally made up many of the things he said I said, and he is already a proven liar and leaker. Where are Memos on Clinton, Lynch & others?",
		"Just heard the Campaign was sued by the Obstructionist Democrats. This can be good news in that we will now counter for the DNC Server that they refused to give to the FBI, the Debbie Wasserman Schultz Servers and Documents held by the Pakistani mystery man and Clinton Emails.",
		"Just heard the Campaign was sued by the Obstructionist Democrats. This can be good news in that we will now counter for the DNC Server that they refused to give to the FBI, the Wendy Wasserman Schultz Servers and Documents held by the Pakistani mystery man and Clinton Emails.",
		"Comey drafted the Crooked Hillary exoneration long before he talked to her (lied in Congress to Senator G), then based his decisions on her poll numbers. Disgruntled, he, McCabe, and the others, committed many crimes!",
		"Comey throws AG Lynch “under the bus!” Why can’t we all find out what happened on the tarmac in the back of the plane with Wild Bill and Lynch? Was she promised a Supreme Court seat, or AG, in order to lay off Hillary. No golf and grandkids talk (give us all a break)!",
		"Unbelievably, James Comey states that Polls, where Crooked Hillary was leading, were a factor in the handling (stupidly) of the Clinton Email probe. In other words, he was making decisions based on the fact that he thought she was going to win, and he wanted a job. Slimeball!",
		"....untruthful slime ball who was, as time has proven, a terrible Director of the FBI. His handling of the Crooked Hillary Clinton case, and the events surrounding it, will go down as one of the worst “botch jobs” of history. It was my great honor to fire James Comey!",
		"I have agreed with the historically cooperative, disciplined approach that we have engaged in with Robert Mueller (Unlike the Clintons!). I have full confidence in Ty Cobb, my Special Counsel, and have been fully advised throughout each phase of this process.",
		"“The FBI closed the case on Hillary, which was a rigged investigation. They exonerated her even before they ever interviewed her, they never even put her under oath.....” and much more. So true Jesse! @WattersWorld",
		"Lawmakers of the House Judiciary Committee are angrily accusing the Department of Justice of missing the Thursday Deadline for turning over UNREDACTED Documents relating to FISA abuse, FBI, Comey, Lynch, McCabe, Clinton Emails and much more. Slow walking - what is going on? BAD!",
		"....lawyer or law firm will take months to get up to speed (if for no other reason than they can bill more), which is unfair to our great country - and I am very happy with my existing team. Besides, there was NO COLLUSION with Russia, except by Crooked Hillary and the Dems!",
		"Remember when they were saying, during the campaign, that Donald Trump is giving great speeches and drawing big crowds, but he is spending much less money and not using social media as well as Crooked Hillary’s large and highly sophisticated staff. Well, not saying that anymore!",
		".....They can help solve problems with North Korea, Syria, Ukraine, ISIS, Iran and even the coming Arms Race. Bush tried to get along, but didn’t have the “smarts.” Obama and Clinton tried, but didn’t have the energy or chemistry (remember RESET). PEACE THROUGH STRENGTH!",
		"Why does the Mueller team have 13 hardened Democrats, some big Crooked Hillary supporters, and Zero Republicans? Another Dem recently added...does anyone think this is fair? And yet, there is NO COLLUSION!",
		"The Mueller probe should never have been started in that there was no collusion and there was no crime. It was based on fraudulent activities and a Fake Dossier paid for by Crooked Hillary and the DNC, and improperly used in FISA COURT for surveillance of my campaign. WITCH HUNT!",
		"...have shown conclusively that there was no Collusion with Russia..just excuse for losing. The only Collusion was that done by the DNC, the Democrats and Crooked Hillary. The writer of the story, Maggie Haberman, a Hillary flunky, knows nothing about me and is not given access.",
		"“He’s got a very good point. Somebody in the Justice Department has a treasure trove of evidence of Mrs. Clinton’s criminality at her own hands, or through others, that ought to be investigated. I fully agree with the President on that.” @judgenapolitano on @marthamaccallum Show",
		"Dem Memo: FBI did not disclose who the clients were - the Clinton Campaign and the DNC. Wow!",
		"....The President Obama quote just before election. That’s because he thought Crooked Hillary was going to win and he didn’t want to “rock the boat.” When I easily won the Electoral College, the whole game changed and the Russian excuse became the narrative of the Dems.",
		"Now that Adam Schiff is starting to blame President Obama for Russian meddling in the election, he is probably doing so as yet another excuse that the Democrats, lead by their fearless leader, Crooked Hillary Clinton, lost the 2016 election. But wasn’t I a great candidate?",
		"“My view is that not only has Trump been vindicated in the last several weeks about the mishandling of the Dossier and the lies about the Clinton/DNC Dossier, it shows that he’s been victimized. He’s been victimized by the Obama Administration who were using all sorts of.......",
		"Wow! -Senator Mark Warner got caught having extensive contact with a lobbyist for a Russian oligarch. Warner did not want a “paper trail” on a “private” meeting (in London) he requested with Steele of fraudulent Dossier fame. All tied into Crooked Hillary.",
		"“The four page memo released Friday reports the disturbing fact about how the FBI and FISA appear to have been used to influence the 2016 election and its aftermath....The FBI failed to inform the FISA court that the Clinton campaign had funded the dossier....the FBI became....",
		"“You had Hillary Clinton and the Democratic Party try to hide the fact that they gave money to GPS Fusion to create a Dossier which was used by their allies in the Obama Administration to convince a Court misleadingly, by all accounts, to spy on the Trump Team.” Tom Fitton, JW",
		"Disproven and paid for by Democrats “Dossier used to spy on Trump Campaign. Did FBI use Intel tool to influence the Election?” @foxandfriends Did Dems or Clinton also pay Russians? Where are hidden and smashed DNC servers? Where are Crooked Hillary Emails? What a mess!",
		"If the Dems (Crooked Hillary) got elected, your stocks would be down 50% from values on Election Day. Now they have a great future - and just beginning! https://t.co/9TzSC8F8vY",
		"WOW, @foxandfrlends “Dossier is bogus. Clinton Campaign, DNC funded Dossier. FBI CANNOT (after all of this time) VERIFY CLAIMS IN DOSSIER OF RUSSIA/TRUMP COLLUSION. FBI TAINTED.” And they used this Crooked Hillary pile of garbage as the basis for going after the Trump Campaign!",
		"(Clinton Puppet), he was using, allegedly, his FBI Official Email Account to promote her campaign. You obviously cannot do this. These were the people who were investigating Hillary Clinton.”",
		"How can FBI Deputy Director Andrew McCabe, the man in charge, along with leakin’ James Comey, of the Phony Hillary Clinton investigation (including her 33,000 illegally deleted emails) be given $700,000 for wife’s campaign by Clinton Puppets during investigation?",
		"Report: “ANTI-TRUMP FBI AGENT LED CLINTON EMAIL PROBE” Now it all starts to make sense!",
		"After years of Comey, with the phony and dishonest Clinton investigation (and more), running the FBI, its reputation is in Tatters - worst in History! But fear not, we will bring it back to greatness.",
		"Tainted (no, very dishonest?) FBI “agent’s role in Clinton probe under review.” Led Clinton Email probe. @foxandfriends Clinton money going to wife of another FBI agent in charge.",
		"RT @paulsperry_: Wray needs to clean house. Now we know the politicization even worse than McCabe's ties to McAuliffe/Clinton. It also infe…",
		"Many people in our Country are asking what the “Justice” Department is going to do about the fact that totally Crooked Hillary, AFTER receiving a subpoena from the United States Congress, deleted and “acid washed” 33,000 Emails? No justice!",
		"So General Flynn lies to the FBI and his life is destroyed, while Crooked Hillary Clinton, on that now famous FBI holiday “interrogation” with no swearing in and no recording, lies many times...and nothing happens to her? Rigged system, or just a double standard?",
		"“Had the information (Crooked Hillary’s emails) been released there would have been harm to National Security....Charles McCullough Fmr Intel Comm Inspector General https://t.co/b0tLW5TVhX", 
		"Charles McCullough, the respected fmr Intel Comm Inspector General, said public was misled on Crooked Hillary Emails. “Emails endangered National Security.” Why aren’t our deep State authorities looking at this? Rigged & corrupt? @TuckerCarlson @seanhannity",
		"Another Crooked Hillary Fan! https://t.co/1LidydhORD",
		"Crooked Hillary Clinton is the worst (and biggest) loser of all time. She just can’t stop, which is so good for the Republican Party. Hillary, get on with your life and give it another try in three years!",
		"Does the Fake News Media remember when Crooked Hillary Clinton, as Secretary of State, was begging Russia to be our friend with the misspelled reset button? Obama tried also, but he had zero chemistry with Putin.",
		"Bernie Sanders supporters have every right to be apoplectic of the complete theft of the Dem primary by Crooked Hillary!",
		"Pocahontas just stated that the Democrats, lead by the legendary Crooked Hillary Clinton, rigged the Primaries! Lets go FBI & Justice Dept.",
		"The real story on Collusion is in Donna B's new book. Crooked Hillary bought the DNC & then stole the Democratic Primary from Crazy Bernie!",
		"Everybody is asking why the Justice Department (and FBI) isn't looking into all of the dishonesty going on with Crooked Hillary & the Dems..",
		"Sorry, but this is years ago, before Paul Manafort was part of the Trump campaign. But why aren't Crooked Hillary & the Dems the focus?????",
		"...are now fighting back like never before. There is so much GUILT by Democrats/Clinton, and now the facts are pouring out. DO SOMETHING!",
		"Never seen such Republican ANGER & UNITY as I have concerning the lack of investigation on Clinton made Fake Dossier (now $12,000,000?),....",
		"“WHAT HAPPENED” “How Team Hillary played the press for fools on Russia” https://t.co/GqpIidk017 NOW WE KNOW! https://t.co/SgWL1HZmkI",
		"Clinton campaign & DNC paid for research that led to the anti-Trump Fake News Dossier. The victim here is the President. @FoxNews",
		"Crooked Hillary Clinton spent hundreds of millions of dollars more on Presidential Election than I did. Facebook was on her side, not mine!",
		".@foxandfriends Russia sent millions to Clinton Foundation",
		"Uranium deal to Russia, with Clinton help and Obama Administration knowledge, is the biggest story that Fake Media doesn't want to follow!",
		"As it has turned out, James Comey lied and leaked and totally protected Hillary Clinton. He was the best thing that ever happened to her!",
		"...people not interviewed, including Clinton herself. Comey stated under oath that he didn't do this-obviously a fix? Where is Justice Dept?",
		"Wow, FBI confirms report that James Comey drafted letter exonerating Crooked Hillary Clinton long before investigation was complete. Many..",
		"I was recently asked if Crooked Hillary Clinton is going to run in 2020? My answer was, I hope so!",
		"Being nice to Rocket Man hasn't worked in 25 years, why would it work now? Clinton failed, Bush failed, and Obama failed. I won't fail.",
		"The greatest influence over our election was the Fake News Media screaming for Crooked Hillary Clinton. Next, she was a bad candidate!",
		"The Russia hoax continues, now it's ads on Facebook. What about the totally biased and dishonest Media coverage in favor of Crooked Hillary?",
		"RT @RealEagleBites: @realDonaldTrump It is the height of hypocrisy. Obama and Clinton in effect gave nuclear weapons to North Korea by thei…",
		"After allowing North Korea to research and build Nukes while Secretary of State (Bill C also), Crooked Hillary now criticizes.",
		"RT @Fuctupmind: @realDonaldTrump Donald Trump's amazing golf swing #CrookedHillary https://t.co/vKhxxFCBV1",
		"The deplorables came back to haunt Hillary.They expressed their feelings loud and clear. She spent big money but, in the end, had no game!",
		"Crooked Hillary Clinton blames everybody (and every thing) but herself for her election loss. She lost the debates and lost her direction!",
		"Wow, looks like James Comey exonerated Hillary Clinton long before the investigation was over...and so much more. A rigged system!",
		"I want to thank Steve Bannon for his service. He came to the campaign during my run against Crooked Hillary Clinton - it was great! Thanks S",
		"E-mails show that the AmazonWashingtonPost and the FailingNewYorkTimes were reluctant to cover the Clinton/Lynch secret meeting in plane.",
		"RT @RightlyNews: What's a high priced Clinton attorney doing representing a low level IT staffer for the Democrats? -@jessebwatters on t…",
		"RT @dcexaminer: Emails show Washington Post, New York Times reporters unenthusiastic about covering Clinton-Lynch meeting https://t.co/PKSL…",
		"...big dollars ($700,000) for his wife's political run from Hillary Clinton and her representatives. Drain the Swamp!",
		"Why didn't A.G. Sessions replace Acting FBI Director Andrew McCabe, a Comey friend who was in charge of Clinton investigation but got....",
		"Problem is that the acting head of the FBI & the person in charge of the Hillary investigation, Andrew McCabe, got $700,000 from H for wife!",
		"Attorney General Jeff Sessions has taken a VERY weak position on Hillary Clinton crimes (where are E-mails & DNC server) & Intel leakers!",
		"Ukrainian efforts to sabotage Trump campaign - quietly working to boost Clinton. So where is the investigation A.G. @seanhannity",
		"So why aren't the Committees and investigators, and of course our beleaguered A.G., looking into Crooked Hillarys crimes & Russia relations?",
		"My son Donald openly gave his e-mails to the media & authorities whereas Crooked Hillary Clinton deleted (& acid washed) her 33,000 e-mails!",
		"...What about all of the Clinton ties to Russia, including Podesta Company, Uranium deal, Russian Reset, big dollar speeches etc.",
		"So many people are asking why isn't the A.G. or Special Council looking at the many Hillary Clinton or Comey crimes. 33,000 e-mails deleted?",
		"HillaryClinton can illegally get the questions to the Debate & delete 33,000 emails but my son Don is being scorned by the Fake News Media?",
		"Why aren't the same standards placed on the Democrats. Look what Hillary Clinton may have gotten away with. Disgraceful!",
		"If Chelsea Clinton were asked to hold the seat for her mother,as her mother gave our country away, the Fake News would say CHELSEA FOR PRES!",
		"RT @foxandfriends: Another Dem 'queasy' over claim of Loretta Lynch meddling in Clinton case https://t.co/wdQ9MduxOO",
		"...and did not want to rock the boat. He didn't choke, he colluded or obstructed, and it did the Dems and Crooked Hillary no good.",
		"The reason that President Obama did NOTHING about Russia after being notified by the CIA of meddling is that he expected Clinton would win..",
		"Hillary Clinton colluded with the Democratic Party in order to beat Crazy Bernie Sanders. Is she allowed to so collude? Unfair to Bernie!",
		"Obama Administration official said they choked when it came to acting on Russian meddling of election. They didn't want to hurt Hillary?",
		"Why is that Hillary Clintons family and Dems dealings with Russia are not looked at, but my non-dealings are?",
		"A.G. Lynch made law enforcement decisions for political purposes...gave Hillary Clinton a free pass and protection. Totally illegal!",
		"Crooked Hillary Clinton now blames everybody but herself, refuses to say she was a terrible candidate. Hits Facebook & even Dems & DNC.",
		"With all of the illegal acts that took place in the Clinton campaign & Obama Administration, there was never a special counsel appointed!",
		"With all of the illegal acts that took place in the Clinton campaign & Obama Administration, there was never a special councel appointed!",
		"FBI Director Comey was the best thing that ever happened to Hillary Clinton in that he gave her a free pass for many bad deeds! The phony...",
		"New polls out today are very good considering that much of the media is FAKE and almost always negative. Would still beat Hillary in .....",
		"Did Hillary Clinton ever apologize for receiving the answers to the debate? Just asking!",
		"Was the brother of John Podesta paid big money to get the sanctions on Russia lifted? Did Hillary know?",
		"Why doesn't Fake News talk about Podesta ties to Russia as covered by @FoxNews or money from Russia to Clinton - sale of Uranium?",
		"...money to Bill, the Hillary Russian reset, praise of Russia by Hillary, or Podesta Russian Company. Trump Russia story is a hoax. #MAGA!",
		"Why isn't the House Intelligence Committee looking into the Bill & Hillary deal that allowed big Uranium to go to Russia, Russian speech....",
		"What about all of the contact with the Clinton campaign and the Russians? Also, is it true that the DNC would not let the FBI in to look?",
		"The race for DNC Chairman was, of course, totally rigged. Bernie's guy, like Bernie himself, never had a chance. Clinton demanded Perez!",
		"This Russian connection non-sense is merely an attempt to cover-up the many mistakes made in Hillary Clinton's losing campaign."
	]
end