module Maga
	TWEETS = [
		"...and voted against the massive Tax Cut Bill. He’s also weak on borders and crime. Sadly, our great Military and Vets mean nothing to Bobby Jr. Lou Barletta will win! #MAGA",
		"Congratulations to Deb Fischer. The people of Nebraska have seen what a great job she is doing - and it showed up at the ballot box! #MAGA",
		"Congratulations to Lou Barletta of Pennsylvania. He will be a great Senator and will represent his people well - like they haven’t been represented in many years. Lou is a friend of mine and a special guy, he will very much help MAKE AMERICA GREAT AGAIN!",
		"Thank you Indiana! #MAGA https://t.co/fCv76VyUax",
		"Join me LIVE in Washington, Michigan at 7:00pmE on @FoxNews! #MAGA",
		"Join me in Washington, Michigan on Saturday, April 28, 2018 at 7:00pm! #MAGA Tickets: https://t.co/DISosdqBuu https://t.co/gHdTgHw5FU",
		"Can you believe that despite 93% bad stories from the Fake News Media (should be getting good stories), today we had just about our highest Poll Numbers, including those on Election Day? The American public is wise to the phony an dishonest press. Make America Great Again!",
		"RT @GOPChairwoman: Crumbs are still coming. #MAGA https://t.co/JFZL6czboZ",
		"RT @GOPChairwoman: We’re in a prime position to defend our majorities in 2018. Let’s defy history. #MAGA #LeadRight https://t.co/fo8g0pSjWQ",
		"Great news! #MAGA https://t.co/mRQGRJkozC",
		".@HowieCarrShow just wrote a book which everyone is talking about. He was a great help. He is a veteran journalist who had a great influence in NH and beyond. He calls it the most amazing political campaign of modern times. The book is called, “What Really Happened.” Enjoy! #MAGA https://t.co/jYhjpoJKHe",
		"My honor Charlie - thank you! #MAGA https://t.co/ZbXFxNVMLP",
		"Larry Kudlow will be my Chief Economic Advisor as Director of the National Economic Council. Our Country will have many years of Great Economic & Financial Success, with low taxes, unparalleled innovation, fair trade and an ever expanding labor force leading the way! #MAGA",
		"Thank you for hosting! #MAGA https://t.co/9pHH60DVlX",
		"Join me LIVE in Moon Township, Pennsylvania at 7:00pmE. Great crowd for a #MAGA rally! https://t.co/PYJNg0WGDL",
		"Look forward to being in Pennsylvania tomorrow in support of Rick @Saccone4PA18. Big crowd expected in Moon Township. Vote Rick and see you there! #MAGA",
		"JOBS, JOBS, JOBS! #MAGA https://t.co/YAaqRcA7ZS",
		"Great meeting with @Cabinet at the @WhiteHouse today! #MAGA https://t.co/InWj0QTosz",
		"From Bush 1 to present, our Country has lost more than 55,000 factories, 6,000,000 manufacturing jobs and accumulated Trade Deficits of more than 12 Trillion Dollars. Last year we had a Trade Deficit of almost 800 Billion Dollars. Bad Policies & Leadership. Must WIN again! #MAGA",
		"@MarkBurnettTV @RealRomaDowney From Bush 1 to present, our Country has lost more than 55,000 factories, 6,000,000 manufacturing jobs and accumulated Trade Deficits of more than 12 Trillion Dollars. Last year we had a Trade Deficit of almost 800 Billion Dollars. Bad policies & leadership. Must win again! #MAGA",
		"We are on the losing side of almost all trade deals. Our friends and enemies have taken advantage of the U.S. for many years. Our Steel and Aluminum industries are dead. Sorry, it’s time for a change! MAKE AMERICA GREAT AGAIN!",
		"Unemployment filings are at their lowest level in over 48 years. Great news for workers and JOBS, JOBS, JOBS! #MAGA https://t.co/SzHTarzfrW",
		"I want to encourage all of my many Texas friends to vote in the primary for Governor Greg Abbott, Senator Ted Cruz, Lt. Gov. Dan Patrick, and Attorney General Ken Paxton. They are helping me to Make America Great Again! Vote early or on March 6th.",
		"What many people don’t understand, or don’t want to understand, is that Wayne, Chris and the folks who work so hard at the @NRA are Great People and Great American Patriots. They love our Country and will do the right thing. MAKE AMERICA GREAT AGAIN!",
		"The journey to #MAGA began @CPAC 2011 and the opportunity to reconnect with friends and supporters is something I look forward to every year. See you at #CPAC2018!",
		"So many positive things going on for the U.S.A. and the Fake News Media just doesn’t want to go there. Same negative stories over and over again! No wonder the People no longer trust the media, whose approval ratings are correctly at their lowest levels in history! #MAGA",
		"With 3.5 million Americans receiving bonuses or other benefits from their employers as a result of TAX CUTS, 2018 is off to great start! Unemployment rate at 4.1%. Average earnings up 2.9% in the last year. 200,000 new American jobs. #MAGA https://t.co/upqSvBhRqJ",
		"Heading back from a very exciting two days in Davos, Switzerland. Speech on America’s economic revival was well received. Many of the people I met will be investing in the U.S.A.! #MAGA",
		"AMERICA will once again be a NATION that thinks big, dreams bigger, and always reaches for the stars. YOU are the ones who will shape America’s destiny. YOU are the ones who will restore our prosperity. And YOU are the ones who are MAKING AMERICA GREAT AGAIN! #MAGA https://t.co/f2abNK47II",
		"During the campaign, I promised to MAKE AMERICA GREAT AGAIN by bringing businesses and jobs back to our country. I am very proud to see companies like Chrysler moving operations from Mexico to Michigan where there are so many great American workers! https://t.co/hz2q9UTfnF",
		"...to stop drugs, they want to take money away from our military which we cannot do.” My standard is very simple, AMERICA FIRST & MAKE AMERICA GREAT AGAIN!",
		"....Because of the Democrats not being interested in life and safety, DACA has now taken a big step backwards. The Dems will threaten “shutdown,” but what they are really doing is shutting down our military, at a time we need it most. Get smart, MAKE AMERICA GREAT AGAIN!",
		"Thank you @GOPLeader Kevin McCarthy! Couldn’t agree w/you more. TOGETHER, we are #MAGA https://t.co/QaxtqpyXTR",
		"I hope everyone is having a great Christmas, then tomorrow it’s back to work in order to Make America Great Again (which is happening faster than anyone anticipated)!",
		"The Fake News refuses to talk about how Big and how Strong our BASE is. They show Fake Polls just like they report Fake News. Despite only negative reporting, we are doing well - nobody is going to beat us. MAKE AMERICA GREAT AGAIN!",
		"Home Sales hit BEST numbers in 10 years! MAKE AMERICA GREAT AGAIN",
		"DOW RISES 5000 POINTS ON THE YEAR FOR THE FIRST TIME EVER - MAKE AMERICA GREAT AGAIN!",
		"When the American People speak, ALL OF US should listen. Just over one year ago, you spoke loud and clear. On November 8, 2016, you voted to MAKE AMERICA GREAT AGAIN! https://t.co/3AOv53S0PU",
		"DOW, S&P 500 and NASDAQ close at record highs! #MAGA https://t.co/hvqwnqSGuG",
		"In 1960, there were approximately 20,000 pages in the Code of Federal Regulations. Today there are over 185,000 pages, as seen in the Roosevelt Room. Today, we CUT THE RED TAPE! It is time to SET FREE OUR DREAMS and MAKE AMERICA GREAT AGAIN! https://t.co/teAVNzjvcx",
		"Consumer Confidence is at an All-Time High, along with a Record High Stock Market. Unemployment is at a 17 year low. MAKE AMERICA GREAT AGAIN! Working to pass MASSIVE TAX CUTS (looking good).",
		"A big contingent of very enthusiastic Roy Moore fans at the rally last night. We can’t have a Pelosi/Schumer Liberal Democrat, Jones, in that important Alabama Senate seat. Need your vote to Make America Great Again! Jones will always vote against what we must do for our Country.",
		"Just arrived at the Pensacola Bay Center. Join me LIVE on @FoxNews in 10 minutes! #MAGA https://t.co/RQFqOkcpNV",
		"On my way to Pensacola, Florida. See everyone soon! #MAGA https://t.co/ijwxVSYQ52",
		"MAKE AMERICA GREAT AGAIN! https://t.co/64a93S07s7",
		"LAST thing the Make America Great Again Agenda needs is a Liberal Democrat in Senate where we have so little margin for victory already. The Pelosi/Schumer Puppet Jones would vote against us 100% of the time. He’s bad on Crime, Life, Border, Vets, Guns & Military. VOTE ROY MOORE!",
		"Big crowd expected today in Pensacola, Florida, for a Make America Great Again speech. We have done so much in so short a period of time...and yet are planning to do so much more! See you there!",
		"MAKE AMERICA GREAT AGAIN!",
		"Our FIFTH 1K milestone of 2017! #DOW24K #MAGA https://t.co/NoVt1uFp0y",
		"Since the first day I took office, all you hear is the phony Democrat excuse for losing the election, Russia, Russia,Russia. Despite this I have the economy booming and have possibly done more than any 10 month President. MAKE AMERICA GREAT AGAIN!",
		"MAKE AMERICA GREAT AGAIN!",
		"@ThePlumLineGS MAKE AMERICA GREAT AGAIN!",
		"One of the most accurate polls last time around. But #FakeNews likes to say we’re in the 30’s. They are wrong. Some people think numbers could be in the 50's. Together, WE will MAKE AMERICA GREAT AGAIN! https://t.co/YhrwkdObhP",
		"Will be leaving the Philippines tomorrow after many days of constant mtgs & work in order to #MAGA! My promises are rapidly being fulfilled.",
		"Congress must end chain migration so that we can have a system that is SECURITY BASED! We need to make AMERICA SAFE! #USA https://t.co/d7L1YW5iVY",
		"Happy birthday to the great @TheLeeGreenwood. You and your beautiful song have made such a difference. MAKE AMERICA GREAT AGAIN!",
		"Happy birthday to the great @leegreenwood83. You and your beautiful song have made such a difference. MAKE AMERICA GREAT AGAIN!",
		"Wacky & totally unhinged Tom Steyer, who has been fighting me and my Make America Great Again agenda from beginning, never wins elections!",
		"Together, we will Make America Great Again! #AmericaFirst https://t.co/ajiC3flNkI",
		"MAKE AMERICA GREAT AGAIN! https://t.co/CbEwJSQ1A3",
		".@DanaPerino & @BradThor, Thank you so much for the wonderful compliment. Working hard! #MAGA https://t.co/AKWlsMsCVH",
		"20,000, 21,000, 22,000, 23,000, this year...FOUR one thousand milestones this year...",
		"...if Congress gives us the massive tax cuts (and reform) I am asking for, those numbers will grow by leaps and bounds. #MAGA",
		"RT @LouDobbs: #AmericaFirst- @KellyannePolls: The Middle Class & businesses will benefit from @POTUS' historic tax revolution. #Dobbs #MAGA…",
		"Just arrived in Indianapolis, Indiana to make an announcement on #TaxReform! Together, we are going to MAKE AMERICA GREAT AGAIN! https://t.co/Dy9UwhkWHL",
		"Spoke to Roy Moore of Alabama last night for the first time. Sounds like a really great guy who ran a fantastic race. He will help to #MAGA!",
		"ALABAMA, get out and vote for Luther Strange - he has proven to me that he will never let you down! #MAGA",
		"Courageous Patriots have fought and died for our great American Flag --- we MUST honor and respect it! MAKE AMERICA GREAT AGAIN!",
		"RT @DonnaWR8: @realDonaldTrump You can boycott our anthem WE CAN BOYCOTT YOU! #NFL #MAGA https://t.co/ryYzZnXjXE",
		"RT @DonnaWR8: .@POTUS #TRUMP & @FLOTUS When ALL seemed HOPELESS...YOU brought HOPE! You INSPIRE us ALL! #MAGA #Harvey @Scavino45 #USA…",
		"RT @DonnaWR8: @realDonaldTrump Thank you @POTUS for believing in Us like we believed in you! #MAGA https://t.co/C476SHWd0m",
		"Big meetings today at the United Nations. So many interesting leaders. America First will MAKE AMERICA GREAT AGAIN!",
		"Important meetings and calls scheduled for today. Military and economy are getting stronger by the day, and our enemies know it. #MAGA",
		"After reading the false reporting and even ferocious anger in some dying magazines, it makes me wonder, WHY? All I want to do is #MAGA!",
		"RT @EricTrump: Honored to speak at the RNC Summer Meeting in Nashville Tennessee this evening! @GOP #MAGA @GOPChairwoman https://t.c…",
		"MAKE AMERICA GREAT AGAIN! https://t.co/RzePiucV3h",
		"See you at 7:00 P.M. tonight Phoenix, Arizona! #MAGA Tickets: https://t.co/2kUQfKqbsx https://t.co/1w3LVkpESE",
		"Just returned to Bedminster, NJ from Camp David. GREAT meeting on National Security, the Border and the Military! #MAGA https://t.co/Hjmcnnse9j",
		"Just landed in Bedminster, New Jersey. #MAGA https://t.co/6EQfmRzrnv",
		"MAKE AMERICA GREAT AGAIN!",
		"Heading to Washington this morning. Much work to do. Focus on trade and military. #MAGA",
		"MAKE AMERICA GREAT AGAIN! https://t.co/g4ELhh9joH",
		"RT @IvankaTrump: Since @realDonaldTrump inauguration, over 1 million net new jobs have been created in the American economy! #MAGA",
		"Thank you West Virginia! All across the country, Americans of every kind are coming together w/one simple goal: to MAKE AMERICA GREAT AGAIN! https://t.co/thRh7htVbH",
		"Just arrived in West Virginia for a MAKE AMERICA GREAT AGAIN rally in Huntington at 7:00pmE. Massive crowd expected - tune in! #MAGA",
		"RT @JacobAWohl: @realDonaldTrump The #MAGA great again movement is WINNING, and the left-wing media can't stand it!",
		"Big progress being made in ridding our country of MS-13 gang members and gang members in general. MAKE AMERICA SAFE AGAIN!",
		"Departing The Pentagon after meetings with @VP Pence, Secretary James Mattis, and our great teams. #MAGA https://t.co/5d1MSzhjQS",
		"MAKE AMERICA GREAT AGAIN! https://t.co/3eYF3nir4B",
		"JOBS, JOBS, JOBS! #MAGA https://t.co/HScS4Y9ZJK",
		"Stock market hits another high with spirit and enthusiasm so positive. Jobs outlook looking very good! #MAGA https://t.co/Vwxsb2vWGe",
		"MAKE AMERICA GREAT AGAIN! https://t.co/NVDVRrWLs4",
		"I will represent our country well and fight for its interests! Fake News Media will never cover me accurately but who cares! We will #MAGA!",
		"My use of social media is not Presidential - it’s MODERN DAY PRESIDENTIAL. Make America Great Again!",
		"MAKE AMERICA SAFE AGAIN! #NoSanctuaryForCriminalsAct #KatesLaw #SaveAmericanLives https://t.co/jbN4hPjqjS",
		"RT @ericbolling: Good morning friends! The Swamp out today. President Trump has a copy... get yours here https://t.co/TntLPNCCjR. #maga…",
		"MAKE AMERICA GREAT AGAIN!",
		"Together, we are going to MAKE AMERICA GREAT AGAIN! #AmericaFirst https://t.co/MVJbs44AtR",
		"Thank you Kirkwood Community College. Heading to the U.S. Cellular Center now for an 8pmE MAKE AMERICA GREAT AGAIN… https://t.co/n6LS32a6Zn",
		"Just landed in Iowa. See everyone soon! #MAGA",
		"Well, the Special Elections are over and those that want to MAKE AMERICA GREAT AGAIN are 5 and O! All the Fake News, all the money spent = 0",
		"The MAKE AMERICA GREAT AGAIN agenda is doing very well despite the distraction of the Witch Hunt. Many new jobs, high business enthusiasm,..",
		"Great news! #MAGA https://t.co/pirHR7lAyT",
		"You are witnessing the single greatest WITCH HUNT in American political history - led by some very bad and conflicted people! #MAGA",
		"Just arrived in Wisconsin to discuss JOBS, JOBS, JOBS! #MAGA https://t.co/lEJ9S817yb",
		"RT @HeyTammyBruce: Coming up at 720a ET on @foxandfriends! See you there! #maga",
		"MAKE AMERICA GREAT AGAIN!",
		"I will be announcing my decision on Paris Accord, Thursday at 3:00 P.M. The White House Rose Garden. MAKE AMERICA GREAT AGAIN!",
		"I will be announcing my decision on the Paris Accord over the next few days. MAKE AMERICA GREAT AGAIN!",
		"Thank you for your support. Together, we will MAKE AMERICA SAFE AND GREAT AGAIN! #POTUSAbroad #USA https://t.co/42vCwr5GkA",
		"Big excitement last night in the Great State of Pennsylvania! Fantastic crowd and people. MAKE AMERICA GREAT AGAIN!",
		"...money to Bill, the Hillary Russian reset, praise of Russia by Hillary, or Podesta Russian Company. Trump Russia story is a hoax. #MAGA!",
		"Thanks you for all of the Trump Rallies today. Amazing support. We will all MAKE AMERICA GREAT AGAIN!",
		"Joined the @HouseGOP Conference this morning at the U.S. Capitol. https://t.co/03e4YBIWr0 #PassTheBill #MAGA… https://t.co/3swdFWGQtP",
		"Thank you Louisville, Kentucky. Together, we will MAKE AMERICA SAFE AND GREAT AGAIN! https://t.co/qGgWEWUvek",
		"Thank you Louisville, Kentucky- on my way! #MAGA https://t.co/3QsBsib6kt",
		"RT @AmericaFirstPol: MAJOR IMPACT: @POTUS Trump is 50 Days in and moving swiftly to get America back on the right track. #MAGA https://t.c…",
		"In Nashville, Tennessee! Lets MAKE AMERICA GREAT AGAIN! https://t.co/m5UR4vv6UH",
		"Weekly Address - 11:00 A.M. at the @WhiteHouse! #MAGA https://t.co/YSaPJnSX2i https://t.co/Gb8iTGzb6j",
		"Great news. We are only just beginning. Together, we are going to #MAGA! https://t.co/BSp685Q9Qf https://t.co/K7yeBZsf6r",
		"Thank you for the great rallies all across the country. Tremendous support. Make America Great Again!",
		"MAKE AMERICA GREAT AGAIN! https://t.co/kuQiZDz4rA",
		"We must fix our education system for our kids to Make America Great Again. Wonderful day at Saint Andrew in Orlando. https://t.co/OTJaHcvLzf",
		"#JointSession #MAGA https://t.co/RDO6Jt2pip",
		"Maybe the millions of people who voted to MAKE AMERICA GREAT AGAIN should have their own rally. It would be the biggest of them all!",
		"HAPPY PRESIDENTS DAY - MAKE AMERICA GREAT AGAIN!",
		"Enjoy the #SuperBowl and then we continue: MAKE AMERICA GREAT AGAIN!",
		"MAKE AMERICA GREAT AGAIN!",
		"Professional anarchists, thugs and paid protesters are proving the point of the millions of people who voted to MAKE AMERICA GREAT AGAIN!",
		"protesters and the tears of Senator Schumer. Secretary Kelly said that all is going well with very few problems. MAKE AMERICA SAFE AGAIN!",
		"Great meeting with automobile industry leaders at the @WhiteHouse this morning. Together, we will #MAGA! https://t.co/OXdiLOkGsZ",
		"THANK YOU for another wonderful evening in Washington, D.C. TOGETHER, we will MAKE AMERICA GREAT AGAIN https://t.co/V3aoj9RUh4",
		"We will follow two simple rules: BUY AMERICAN & HIRE AMERICAN! #InaugurationDay #MAGA",
		"the American people. I have no doubt that we will, together, MAKE AMERICA GREAT AGAIN!"
	]
end