module Obama
	TWEETS = [
		"I hereby demand, and will do so officially tomorrow, that the Department of Justice look into whether or not the FBI/DOJ infiltrated or surveilled the Trump Campaign for Political Purposes - and if any such demands or requests were made by people within the Obama Administration!",
		"....At what point does this soon to be $20,000,000 Witch Hunt, composed of 13 Angry and Heavily Conflicted Democrats and two people who have worked for Obama for 8 years, STOP! They have found no Collussion with Russia, No Obstruction, but they aren’t looking at the corruption...",
		"Wow, word seems to be coming out that the Obama FBI “SPIED ON THE TRUMP CAMPAIGN WITH AN EMBEDDED INFORMANT.” Andrew McCarthy says, “There’s probably no doubt that they had at least one confidential informant in the campaign.” If so, this is bigger than Watergate!",
		"Iran’s Military Budget is up more than 40% since the Obama negotiated Nuclear Deal was reached...just another indicator that it was all a big lie. But not anymore!",
		"Senator Cryin’ Chuck Schumer fought hard against the Bad Iran Deal, even going at it with President Obama, & then Voted AGAINST it! Now he says I should not have terminated the deal - but he doesn’t really believe that! Same with Comey. Thought he was terrible until I fired him!",
		"Just hit 50% in the Rasmussen Poll, much higher than President Obama at same point. With all of the phony stories and Fake News, it’s hard to believe! Thank you America, we are doing Great Things.",
		"Would only join TPP if the deal were substantially better than the deal offered to Pres. Obama. We already have BILATERAL deals with six of the eleven nations in TPP, and are working to make a deal with the biggest of those nations, Japan, who has hit us hard on trade for years!",
		"Much of the bad blood with Russia is caused by the Fake & Corrupt Russia Investigation, headed up by the all Democrat loyalists, or people that worked for Obama. Mueller is most conflicted of all (except Rosenstein who signed FISA & Comey letter). No Collusion, so they go crazy!",
		"If President Obama had crossed his stated Red Line In The Sand, the Syrian disaster would have ended long ago! Animal Assad would have been history!",
		"Our Border Laws are very weak while those of Mexico & Canada are very strong. Congress must change these Obama era, and other, laws NOW! The Democrats stand in our way - they want people to pour into our country unchecked....CRIME! We will be taking strong action today.",
		"Thank you to Rasmussen for the honest polling. Just hit 50%, which is higher than Cheatin’ Obama at the same time in his Administration.",
		"“President Trump's approval rate among likely U.S. voters hit 50 percent on Monday, which puts him higher than former President Barack Obama's score at the same point into his first term, according to a new poll.” Via: @Anna_Giaritelli @DCExaminer https://t.co/ZzycNoDCQJ",
		"As ridiculous as it sounds, the laws of our country do not easily allow us to send those crossing our Southern Border back where they came from. A whole big wasted procedure must take place. Mexico & Canada have tough immigration laws, whereas ours are an Obama joke. ACT CONGRESS",
		"Obama Administration legalized bump stocks. BAD IDEA. As I promised, today the Department of Justice will issue the rule banning BUMP STOCKS with a mandated comment period. We will BAN all devices that turn legal weapons into illegal machine guns.",
		"House Intelligence Committee votes to release final report. FINDINGS: (1) No evidence provided of Collusion between Trump Campaign & Russia. (2) The Obama Administrations Post election response was insufficient. (3) Clapper provided inconsistent testimony on media contacts.",
		".....They can help solve problems with North Korea, Syria, Ukraine, ISIS, Iran and even the coming Arms Race. Bush tried to get along, but didn’t have the “smarts.” Obama and Clinton tried, but didn’t have the energy or chemistry (remember RESET). PEACE THROUGH STRENGTH!",
		"I called President Putin of Russia to congratulate him on his election victory (in past, Obama called him also). The Fake News Media is crazed because they wanted me to excoriate him. They are wrong! Getting along with Russia (and others) is a good thing, not a bad thing.......",
		"Rasmussen and others have my approval ratings at around 50%, which is higher than Obama, and yet the political pundits love saying my approval ratings are “somewhat low.” They know they are lying when they say it. Turn off the show - FAKE NEWS!",
		"Federal Judge in Maryland has just ruled that “President Trump has the right to end DACA.” President Obama had 8 years to fix this problem, and didn’t. I am waiting for the Dems, they are running for the hills!",
		"Why did the Obama Administration start an investigation into the Trump Campaign (with zero proof of wrongdoing) long before the Election in November? Wanted to discredit so Crooked H would win. Unprecedented. Bigger than Watergate! Plus, Obama did NOTHING about Russian meddling.",
		"Why is A.G. Jeff Sessions asking the Inspector General to investigate potentially massive FISA abuse. Will take forever, has no prosecutorial power and already late with reports on Comey etc. Isn’t the I.G. an Obama guy? Why not use Justice Department lawyers? DISGRACEFUL!",
		"“Russians had no compromising information on Donald Trump” @FoxNews Of course not, because there is none, and never was. This whole Witch Hunt is an illegal disgrace...and Obama did nothing about Russia!",
		"Question: If all of the Russian meddling took place during the Obama Administration, right up to January 20th, why aren’t they the subject of the investigation? Why didn’t Obama do something about the meddling? Why aren’t Dem crimes under investigation? Ask Jeff Sessions!",
		"I have been much tougher on Russia than Obama, just look at the facts. Total Fake News!",
		"Matt Schlapp and CPAC are getting ready for another exciting event. Big difference from those days when President Obama held the White House. You’ve come a long way Matt!",
		"....The President Obama quote just before election. That’s because he thought Crooked Hillary was going to win and he didn’t want to “rock the boat.” When I easily won the Electoral College, the whole game changed and the Russian excuse became the narrative of the Dems.",
		"Thank you to @foxandfriends for the great timeline on all of the failures the Obama Administration had against Russia, including Crimea, Syria and so much more. We are now starting to win again!",
		"Obama was President up to, and beyond, the 2016 Election. So why didn’t he do something about Russian meddling?",
		"Now that Adam Schiff is starting to blame President Obama for Russian meddling in the election, he is probably doing so as yet another excuse that the Democrats, lead by their fearless leader, Crooked Hillary Clinton, lost the 2016 election. But wasn’t I a great candidate?",
		"Finally, Liddle’ Adam Schiff, the leakin’ monster of no control, is now blaming the Obama Administration for Russian meddling in the 2016 Election. He is finally right about something. Obama was President, knew of the threat, and did nothing. Thank you Adam!",
		"Never gotten over the fact that Obama was able to send $1.7 Billion Dollars in CASH to Iran and nobody in Congress, the FBI or Justice called for an investigation!",
		"Just like they don’t want to solve the DACA problem, why didn’t the Democrats pass gun control legislation when they had both the House & Senate during the Obama Administration. Because they didn’t want to, and now they just talk!",
		"“My view is that not only has Trump been vindicated in the last several weeks about the mishandling of the Dossier and the lies about the Clinton/DNC Dossier, it shows that he’s been victimized. He’s been victimized by the Obama Administration who were using all sorts of.......",
		"“You had Hillary Clinton and the Democratic Party try to hide the fact that they gave money to GPS Fusion to create a Dossier which was used by their allies in the Obama Administration to convince a Court misleadingly, by all accounts, to spy on the Trump Team.” Tom Fitton, JW",
		"...big unnecessary regulation cuts made it all possible” (among many other things). “President Trump reversed the policies of President Obama, and reversed our economic decline.” Thank you Stuart Varney. @foxandfriends",
		"Reason I canceled my trip to London is that I am not a big fan of the Obama Administration having sold perhaps the best located and finest embassy in London for “peanuts,” only to build a new one in an off location for 1.2 billion dollars. Bad deal. Wanted me to cut ribbon-NO!",
		"On Taxes: “This is the biggest corporate rate cut ever, going back to the corporate income tax rate of roughly 80 years ago.This is a huge pro-growth stimulus for the economy. Every year the Obama WH overstated how the economy would grow. Now real economics and jobs.” @WSJ Report",
		"RT @charliekirk11: ISIS getting slaughtered: Square miles liberated from ISIS Trump: 26,000 -- Obama: 13,200 Total Square miles held by…",
		"While the Fake News loves to talk about my so-called low approval rating, @foxandfriends just showed that my rating on Dec. 28, 2017, was approximately the same as President Obama on Dec. 28, 2009, which was 47%...and this despite massive negative Trump coverage & Russia hoax!",
		"The Kate Steinle killer came back and back over the weakly protected Obama border, always committing crimes and being violent, and yet this info was not used in court. His exoneration is a complete travesty of justice. BUILD THE WALL!",
		"Funny to hear the Democrats talking about the National Debt when President Obama doubled it in only 8 years!",
		"Does the Fake News Media remember when Crooked Hillary Clinton, as Secretary of State, was begging Russia to be our friend with the misspelled reset button? Obama tried also, but he had zero chemistry with Putin.",
		"Report out that Obama Campaign paid $972,000 to Fusion GPS. The firm also got $12,400,000 (really?) from DNC. Nobody knows who OK'd!",
		"RT @USArmy333: @804StreetMedia @realDonaldTrump He’s done more in 9 months then obama did in8 yrs",
		"Uranium deal to Russia, with Clinton help and Obama Administration knowledge, is the biggest story that Fake Media doesn't want to follow!",
		"Dem Senator Schumer hated the Iran deal made by President Obama, but now that I am involved, he is OK with it. Tell that to Israel, Chuck!",
		"Being nice to Rocket Man hasn't worked in 25 years, why would it work now? Clinton failed, Bush failed, and Obama failed. I won't fail.",
		"RT @RealEagleBites: @realDonaldTrump It is the height of hypocrisy. Obama and Clinton in effect gave nuclear weapons to North Korea by thei…",
		"We have made more progress in the last nine months against ISIS than the Obama Administration has made in 8 years.Must be proactive & nasty!",
		"Congress now has 6 months to legalize DACA (something the Obama Administration was unable to do). If they can't, I will revisit this issue!",
		"@foxandfriends According to report just out, President Obama knew about Russian interference 3 years ago but he didn't want to anger Russia!",
		"RT @FoxNews: .@AlanDersh: Trump Has 'More Credibility' Than Obama With North Korea https://t.co/0w1L01EL0q https://t.co/9Q3FYUmNy1",
		"RT @ProgressPolls: Who is a better President of the United States? #ObamaDay",
		"RT @TheFive: @POTUS being unpredictable is a big asset, North Korea knew exactly what President Obama was going to do.- @jessebwatters",
		"RT @AmbJohnBolton: Our country & civilians are vulnerable today because @BarackObama did not believe in national missile defense. Let’s nev…",
		"RT @RealJamesWoods: Only now with a #RealPresident do we see the scope of destruction engineered by #Obama and the #Democrat cabal. @realD…",
		"...have it. Fake News said 17 intel agencies when actually 4 (had to apologize). Why did Obama do NOTHING when he had info before election?",
		"LOVED talking about stock market rallies! Now they barely mention new a…",
		"From @FoxNews Bombshell: In 2016, Obama dismissed idea that anyone could rig an American election. Check out his statement - Witch Hunt!",
		"The real story is that President Obama did NOTHING after being informed in August about Russian meddling. With 4 months looking at Russia...",
		"The reason that President Obama did NOTHING about Russia after being notified by the CIA of meddling is that he expected Clinton would win..",
		"Obama Administration official said they choked when it came to acting on Russian meddling of election. They didn't want to hurt Hillary?",
		"Since the Obama Administration was told way before the 2016 Election that the Russians were meddling, why no action? Focus on them, not T!",
		"Just out: The Obama Administration knew far in advance of November 8th about election meddling by Russia. Did nothing about it. WHY?",
		"By the way, if Russia was working so hard on the 2016 Election, it all took place during the Obama Admin. Why didn't they stop them?",
		"RT @DonaldJTrumpJr: Not surprising at all! Father Of Otto Warmbier: Obama Admin Told Us To Keep Quiet, Trump Admin Brought Him Home https…",
		"The big story is the unmasking and surveillance of people that took place during the Obama Administration.",
		"With all of the illegal acts that took place in the Clinton campaign & Obama Administration, there was never a special counsel appointed!",
		"General Flynn was given the highest security clearance by the Obama Administration - but the Fake News seldom likes talking about that.",
		"Rexnord of Indiana made a deal during the Obama Administration to move to Mexico. Fired their employees. Tax product big that's sold in U.S.",
		"Susan Rice, the former National Security Advisor to President Obama, is refusing to testify before a Senate Subcommittee next week on.....",
		"RT @foxandfriends: Former President Obama's $400K Wall Street speech stuns liberal base; Sen. Warren saying she was troubled by that http…",
		"The weak illegal immigration policies of the Obama Admin. allowed bad MS 13 gangs to form in cities across U.S. We are removing them fast!",
		"When will Sleepy Eyes Chuck Todd and @NBCNews start talking about the Obama SURVEILLANCE SCANDAL and stop with the Fake Trump/Russia story?",
		"RT @mitchellvii: EXACTLY AS I SAID - House Intel Chair: We Cannot Rule Out Sr. Obama Officials Were Involved in Trump Surveillance https://…",
		"Can you imagine what the outcry would be if @SnoopDogg, failing career and all, had aimed and fired the gun at President Obama? Jail time!",
		"For eight years Russia ran over President Obama, got stronger and stronger, picked-off Crimea and added missiles. Weak! @foxandfriends",
		"122 vicious prisoners, released by the Obama Administration from Gitmo, have returned to the battlefield. Just another terrible decision!",
		"How low has President Obama gone to tapp my phones during the very sacred election process. This is Nixon/Watergate. Bad (or sick) guy!",
		"I'd bet a good lawyer could make a great case out of the fact that President Obama was tapping my phones in October, just prior to Election!",
		"Just out: The same Russian Ambassador that met Jeff Sessions visited the Obama White House 22 times, and 4 times last year alone.",
		"Terrible! Just found out that Obama had my wires tapped in Trump Tower just before the victory. Nothing found. This is McCarthyism!",
		"The first meeting Jeff Sessions had with the Russian Amb was set up by the Obama Administration under education program for 100 Ambs......",
		"The media has not reported that the National Debt in my first month went down by $12 billion vs a $200 billion increase in Obama first mo.",
		"'Trump signs bill undoing Obama coal mining rule' https://t.co/yMfT5r5RGh",
		"Crimea was TAKEN by Russia during the Obama Administration. Was Obama too soft on Russia?",
		"I don't know Putin, have no deals in Russia, and the haters are going crazy - yet Obama can make a deal with Iran, #1 in terror, no problem!",
		"Iran is playing with fire - they don't appreciate how kind President Obama was to them. Not me!",
		"Do you believe it? The Obama Administration agreed to take thousands of illegal immigrants from Australia. Why? I will study this dumb deal!",
		"The Democrats are delaying my cabinet picks for purely political reasons. They have nothing going but to obstruct. Now have an Obama A.G."
	]
end