module Russia
	TWEETS = [
		"The Witch Hunt finds no Collusion with Russia - so now they’re looking at the rest of the World. Oh’ great!",
		"Now that the Witch Hunt has given up on Russia and is looking at the rest of the World, they should easily be able to take it into the Mid-Term Elections where they can put some hurt on the Republican Party. Don’t worry about Dems FISA Abuse, missing Emails or Fraudulent Dossier!",
		"....At what point does this soon to be $20,000,000 Witch Hunt, composed of 13 Angry and Heavily Conflicted Democrats and two people who have worked for Obama for 8 years, STOP! They have found no Collussion with Russia, No Obstruction, but they aren’t looking at the corruption...",
		"Things are really getting ridiculous. The Failing and Crooked (but not as Crooked as Hillary Clinton) @nytimes has done a long & boring story indicating that the World’s most expensive Witch Hunt has found nothing on Russia & me so now they are looking at the rest of the World!",
		"Reports are there was indeed at least one FBI representative implanted, for political purposes, into my campaign for president. It took place very early on, and long before the phony Russia Hoax became a “hot” Fake News story. If true - all time biggest political scandal!",
		"Can you believe that with all of the made up, unsourced stories I get from the Fake News Media, together with the $10,000,000 Russian Witch Hunt (there is no Collusion), I now have my best Poll Numbers in a year. Much of the Media may be corrupt, but the People truly get it!",
		"The 13 Angry Democrats in charge of the Russian Witch Hunt are starting to find out that there is a Court System in place that actually protects people from injustice...and just wait ‘till the Courts get to see your unrevealed Conflicts of Interest!",
		"The Russia Witch Hunt is rapidly losing credibility. House Intelligence Committee found No Collusion, Coordination or anything else with Russia. So now the Probe says OK, what else is there? How about Obstruction for a made up, phony crime.There is no O, it’s called Fighting Back",
		"“This isn’t some game. You are screwing with the work of the president of the United States.” John Dowd, March 2018. With North Korea, China, the Middle East and so much more, there is not much time to be thinking about this, especially since there was no Russian “Collusion.”",
		"NEW BOOK - A MUST READ! “The Russia Hoax - The Illicit Scheme to Clear Hillary Clinton and Frame Donald Trump” by the brilliant Fox News Legal Analyst Gregg Jarrett. A sad chapter for law enforcement. A rigged system!",
		"So disgraceful that the questions concerning the Russian Witch Hunt were “leaked” to the media. No questions on Collusion. Oh, I see...you have a made up, phony crime, Collusion, that never existed, and an investigation begun with illegally leaked classified information. Nice!",
		"Secret Service has just informed me that Senator Jon Tester’s statements on Admiral Jackson are not true. There were no such findings. A horrible thing that we in D.C. must live with, just like phony Russian Collusion. Tester should lose race in Montana. Very dishonest and sick!",
		"House Intelligence Committee rules that there was NO COLLUSION between the Trump Campaign and Russia. As I have been saying all along, it is all a big Hoax by the Democrats based on payments and lies. There should never have been a Special Counsel appointed. Witch Hunt!",
		"House Intelligence Committee rules that there was NO COLLUSION between the Trump Campaign and Russia. As I have been saying all along, it is all a big Hoax by the Democrats based on payments and lies. There should never have been a Special Councel appointed. Witch Hunt!",
		"Just Out: House Intelligence Committee Report released. “No evidence” that the Trump Campaign “colluded, coordinated or conspired with Russia.” Clinton Campaign paid for Opposition Research obtained from Russia- Wow! A total Witch Hunt! MUST END NOW!",
		"Slippery James Comey, the worst FBI Director in history, was not fired because of the phony Russia investigation where, by the way, there was NO COLLUSION (except by the Dems)!",
		"Russia and China are playing the Currency Devaluation game as the U.S. keeps raising interest rates. Not acceptable!",
		"Much of the bad blood with Russia is caused by the Fake & Corrupt Russia Investigation, headed up by the all Democrat loyalists, or people that worked for Obama. Mueller is most conflicted of all (except Rosenstein who signed FISA & Comey letter). No Collusion, so they go crazy!",
		"Our relationship with Russia is worse now than it has ever been, and that includes the Cold War. There is no reason for this. Russia needs us to help with their economy, something that would be very easy to do, and we need all nations to work together. Stop the arms race?",
		"Russia vows to shoot down any and all missiles fired at Syria. Get ready Russia, because they will be coming, nice and new and “smart!” You shouldn’t be partners with a Gas Killing Animal who kills his people and enjoys it!",
		"....doing things that nobody thought possible, despite the never ending and corrupt Russia Investigation, which takes tremendous time and focus. No Collusion or Obstruction (other than I fight back), so now they do the Unthinkable, and RAID a lawyers office for information! BAD!",
		"The Failing New York Times wrote another phony story. It was political pundit Doug Schoen, not a Ukrainian businessman, who asked me to do a short speech by phone (Skype), hosted by Doug, in Ukraine. I was very positive about Ukraine-another negative to the Fake Russia C story!",
		"Many dead, including women and children, in mindless CHEMICAL attack in Syria. Area of atrocity is in lockdown and encircled by Syrian Army, making it completely inaccessible to outside world. President Putin, Russia and Iran are responsible for backing Animal Assad. Big price...",
		"....lawyer or law firm will take months to get up to speed (if for no other reason than they can bill more), which is unfair to our great country - and I am very happy with my existing team. Besides, there was NO COLLUSION with Russia, except by Crooked Hillary and the Dems!",
		"Many lawyers and top law firms want to represent me in the Russia case...don’t believe the Fake News narrative that it is hard to find a lawyer who wants to take this on. Fame & fortune will NEVER be turned down by a lawyer, though some are conflicted. Problem is that a new......",
		"House Intelligence Committee votes to release final report. FINDINGS: (1) No evidence provided of Collusion between Trump Campaign & Russia. (2) The Obama Administrations Post election response was insufficient. (3) Clapper provided inconsistent testimony on media contacts.",
		"I called President Putin of Russia to congratulate him on his election victory (in past, Obama called him also). The Fake News Media is crazed because they wanted me to excoriate him. They are wrong! Getting along with Russia (and others) is a good thing, not a bad thing.......",
		"As the House Intelligence Committee has concluded, there was no collusion between Russia and the Trump Campaign. As many are now finding out, however, there was tremendous leaking, lying and corruption at the highest levels of the FBI, Justice & State. #DrainTheSwamp",
		"THE HOUSE INTELLIGENCE COMMITTEE HAS, AFTER A 14 MONTH LONG IN-DEPTH INVESTIGATION, FOUND NO EVIDENCE OF COLLUSION OR COORDINATION BETWEEN THE TRUMP CAMPAIGN AND RUSSIA TO INFLUENCE THE 2016 PRESIDENTIAL ELECTION.",
		"...have shown conclusively that there was no Collusion with Russia..just excuse for losing. The only Collusion was that done by the DNC, the Democrats and Crooked Hillary. The writer of the story, Maggie Haberman, a Hillary flunky, knows nothing about me and is not given access.",
		"The Failing New York Times purposely wrote a false story stating that I am unhappy with my legal team on the Russia case and am going to add another lawyer to help out. Wrong. I am VERY happy with my lawyers, John Dowd, Ty Cobb and Jay Sekulow. They are doing a great job and.....",
		"Why did the Obama Administration start an investigation into the Trump Campaign (with zero proof of wrongdoing) long before the Election in November? Wanted to discredit so Crooked H would win. Unprecedented. Bigger than Watergate! Plus, Obama did NOTHING about Russian meddling.",
		"“Russians had no compromising information on Donald Trump” @FoxNews Of course not, because there is none, and never was. This whole Witch Hunt is an illegal disgrace...and Obama did nothing about Russia!",
		"Question: If all of the Russian meddling took place during the Obama Administration, right up to January 20th, why aren’t they the subject of the investigation? Why didn’t Obama do something about the meddling? Why aren’t Dem crimes under investigation? Ask Jeff Sessions!",
		"Bad ratings @CNN & @MSNBC got scammed when they covered the anti-Trump Russia rally wall-to-wall. They probably knew it was Fake News but, because it was a rally against me, they pushed it hard anyway. Two really dishonest newscasters, but the public is wise!",
		"I have been much tougher on Russia than Obama, just look at the facts. Total Fake News!",
		"....The President Obama quote just before election. That’s because he thought Crooked Hillary was going to win and he didn’t want to “rock the boat.” When I easily won the Electoral College, the whole game changed and the Russian excuse became the narrative of the Dems.",
		"Thank you to @foxandfriends for the great timeline on all of the failures the Obama Administration had against Russia, including Crimea, Syria and so much more. We are now starting to win again!",
		"Obama was President up to, and beyond, the 2016 Election. So why didn’t he do something about Russian meddling?",
		"Thank you to KenStarr, former Independent Counsel, Whitewater, for your insight and powerful words on FISA abuse, Russian meddling etc. Really great interview with @MariaBartiromo",
		"If it was the GOAL of Russia to create discord, disruption and chaos within the U.S. then, with all of the Committee Hearings, Investigations and Party hatred, they have succeeded beyond their wildest dreams. They are laughing their asses off in Moscow. Get smart America!",
		"Now that Adam Schiff is starting to blame President Obama for Russian meddling in the election, he is probably doing so as yet another excuse that the Democrats, lead by their fearless leader, Crooked Hillary Clinton, lost the 2016 election. But wasn’t I a great candidate?",
		"I never said Russia did not meddle in the election, I said “it may be Russia, or China or another country or group, or it may be a 400 pound genius sitting in bed and playing with his computer.” The Russian “hoax” was that the Trump campaign colluded with Russia - it never did!",
		"Finally, Liddle’ Adam Schiff, the leakin’ monster of no control, is now blaming the Obama Administration for Russian meddling in the 2016 Election. He is finally right about something. Obama was President, knew of the threat, and did nothing. Thank you Adam!",
		"General McMaster forgot to say that the results of the 2016 election were not impacted or changed by the Russians and that the only Collusion was between Russia and Crooked H, the DNC and the Dems. Remember the Dirty Dossier, Uranium, Speeches, Emails and the Podesta Company!",
		"Very sad that the FBI missed all of the many signals sent out by the Florida school shooter. This is not acceptable. They are spending too much time trying to prove Russian collusion with the Trump campaign - there is no collusion. Get back to the basics and make us all proud!",
		"“I have seen all of the Russian ads and I can say very definitively that swaying the election was *NOT* the main goal.” Rob Goldman Vice President of Facebook Ads https://t.co/A5ft7cGJkE",
		"Funny how the Fake News Media doesn’t want to say that the Russian group was formed in 2014, long before my run for President. Maybe they knew I was going to run even though I didn’t know!",
		"“Charges Deal Don A Big Win,” written by Michael Goodwin of the @nypost, succinctly states that “the Russians had no impact on the election results.” There was no Collusion with the Trump Campaign. “She lost the old-fashioned way, by being a terrible candidate. Case closed.”",
		"Russia started their anti-US campaign in 2014, long before I announced that I would run for President. The results of the election were not impacted. The Trump campaign did nothing wrong - no collusion!",
		"According to the @nytimes, a Russian sold phony secrets on “Trump” to the U.S. Asking price was $10 million, brought down to $1 million to be paid over time. I hope people are now seeing & understanding what is going on here. It is all now starting to come out - DRAIN THE SWAMP!",
		"Wow! -Senator Mark Warner got caught having extensive contact with a lobbyist for a Russian oligarch. Warner did not want a “paper trail” on a “private” meeting (in London) he requested with Steele of fraudulent Dossier fame. All tied into Crooked Hillary.",
		"Great jobs numbers and finally, after many years, rising wages- and nobody even talks about them. Only Russia, Russia, Russia, despite the fact that, after a year of looking, there is No Collusion!",
		"This memo totally vindicates “Trump” in probe. But the Russian Witch Hunt goes on and on. Their was no Collusion and there was no Obstruction (the word now used because, after one year of looking endlessly and finding NOTHING, collusion is dead). This is an American disgrace!",
		"Do you notice the Fake News Mainstream Media never likes covering the great and record setting economic news, but rather talks about anything negative or that can be turned into the negative. The Russian Collusion Hoax is dead, except as it pertains to the Dems. Public gets it!",
		"RT @paulsperry_: Fusion GPS, firm behind disputed Russia dossier, retracts its claim of FBI mole in Trump camp https://t.co/s6CFPXSVqb",
		"Disproven and paid for by Democrats “Dossier used to spy on Trump Campaign. Did FBI use Intel tool to influence the Election?” @foxandfriends Did Dems or Clinton also pay Russians? Where are hidden and smashed DNC servers? Where are Crooked Hillary Emails? What a mess!",
		"The single greatest Witch Hunt in American history continues. There was no collusion, everybody including the Dems knows there was no collusion, & yet on and on it goes. Russia & the world is laughing at the stupidity they are witnessing. Republicans should finally take control!",
		"The fact that Sneaky Dianne Feinstein, who has on numerous occasions stated that collusion between Trump/Russia has not been found, would release testimony in such an underhanded and possibly illegal way, totally without authorization, is a disgrace. Must have tough Primary!",
		"While the Fake News loves to talk about my so-called low approval rating, @foxandfriends just showed that my rating on Dec. 28, 2017, was approximately the same as President Obama on Dec. 28, 2009, which was 47%...and this despite massive negative Trump coverage & Russia hoax!",
		"WOW, @foxandfrlends “Dossier is bogus. Clinton Campaign, DNC funded Dossier. FBI CANNOT (after all of this time) VERIFY CLAIMS IN DOSSIER OF RUSSIA/TRUMP COLLUSION. FBI TAINTED.” And they used this Crooked Hillary pile of garbage as the basis for going after the Trump Campaign!",
		"Despite thousands of hours wasted and many millions of dollars spent, the Democrats have been unable to show any collusion with Russia - so now they are moving on to the false accusations and fabricated stories of women who I don’t know and/or have never met. FAKE NEWS!",
		"Congratulations to @ABC News for suspending Brian Ross for his horrendously inaccurate and dishonest report on the Russia, Russia, Russia Witch Hunt. More Networks and “papers” should do the same with their Fake News!",
		"The Chinese Envoy, who just returned from North Korea, seems to have had no impact on Little Rocket Man. Hard to believe his people, and the military, put up with living in such horrible conditions. Russia and China condemned the launch.",
		"Since the first day I took office, all you hear is the phony Democrat excuse for losing the election, Russia, Russia,Russia. Despite this I have the economy booming and have possibly done more than any 10 month President. MAKE AMERICA GREAT AGAIN!",
		"Does the Fake News Media remember when Crooked Hillary Clinton, as Secretary of State, was begging Russia to be our friend with the misspelled reset button? Obama tried also, but he had zero chemistry with Putin.",
		"When will all the haters and fools out there realize that having a good relationship with Russia is a good thing, not a bad thing. There always playing politics - bad for our country. I want to solve North Korea, Syria, Ukraine, terrorism, and Russia can greatly help!",
		"Met with President Putin of Russia who was at #APEC meetings. Good discussions on Syria. Hope for his help to solve, along with China the dangerous North Korea crisis. Progress being made.",
		"All of this Russia talk right when the Republicans are making their big push for historic Tax Cuts & Reform. Is this coincidental? NOT!",
		"...the Uranium to Russia deal, the 33,000 plus deleted Emails, the Comey fix and so much more. Instead they look at phony Trump/Russia,....",
		"“WHAT HAPPENED” “How Team Hillary played the press for fools on Russia” https://t.co/GqpIidk017 NOW WE KNOW! https://t.co/SgWL1HZmkI",
		".@FoxNews Chris Wallace: “More evidence of Dem collusion with Russia than GOP” https://t.co/nACQerJSiu",
		"It is now commonly agreed, after many months of COSTLY looking, that there was NO collusion between Russia and Trump. Was collusion with HC!",
		".@foxandfriends Russia sent millions to Clinton Foundation",
		"Workers of firm involved with the discredited and Fake Dossier take the 5th. Who paid for it, Russia, the FBI or the Dems (or all)?",
		"Uranium deal to Russia, with Clinton help and Obama Administration knowledge, is the biggest story that Fake Media doesn't want to follow!",
		"The Russia hoax continues, now it's ads on Facebook. What about the totally biased and dishonest Media coverage in favor of Crooked Hillary?",
		"@foxandfriends According to report just out, President Obama knew about Russian interference 3 years ago but he didn't want to anger Russia!",
		"Interesting to watch Senator Richard Blumenthal of Connecticut talking about hoax Russian collusion when he was a phony Vietnam con artist!",
		"...and West Virginia. The fact is the Fake News Russian collusion story, record Stock Market, border security, military strength, jobs.....",
		"The United Nations Security Council just voted 15-0 to sanction North Korea. China and Russia voted with us. Very big financial impact!",
		"Our relationship with Russia is at an all-time & very dangerous low. You can thank Congress, the same people that can't even give us HCare!",
		"In other words, Russia was against Trump in the 2016 Election - and why not, I want strong military & low oil prices. Witch Hunt! https://t.co/mMSxj4Su5z",
		"One of the things that has been lost in the politics of this situation is that the Russians collected and spread negative information.....",
		"Jared Kushner did very well yesterday in proving he did not collude with the Russians. Witch Hunt. Next up, 11 year old Barron Trump!",
		"Sleazy Adam Schiff, the totally biased Congressman looking into Russia, spends all of his time on television pushing the Dem loss excuse!",
		"So why aren't the Committees and investigators, and of course our beleaguered A.G., looking into Crooked Hillarys crimes & Russia relations?",
		"After 1 year of investigation with Zero evidence being found, Chuck Schumer just stated that Democrats should blame ourselves,not Russia.",
		"RT @realDonaldTrump: As the phony Russian Witch Hunt continues, two groups are laughing at this excuse for a lost election taking hold, Dem…",
		"As the phony Russian Witch Hunt continues, two groups are laughing at this excuse for a lost election taking hold, Democrats and Russians!",
		"...What about all of the Clinton ties to Russia, including Podesta Company, Uranium deal, Russian Reset, big dollar speeches etc.",
		"Fake News story of secret dinner with Putin is sick. All G 20 leaders, and spouses, were invited by the Chancellor of Germany. Press knew!",
		"Thank you to former campaign adviser Michael Caputo for saying so powerfully that there was no Russian collusion in our winning campaign.",
		"Stock Market hit another all-time high yesterday - despite the Russian hoax story! Also, jobs numbers are starting to look very good!",
		"RT @FoxNews: .@jessebwatters on @DonaldJTrumpJr meeting with Russian attorney: I believe Don Jr. is the victim here. #TheFive https://t.c…",
		"The fact that President Putin and I discussed a Cyber Security unit doesn't mean I think it can happen. It can't-but a ceasefire can,& did!",
		"Sanctions were not discussed at my meeting with President Putin. Nothing will be done until the Ukrainian & Syrian problems are solved!",
		"Putin & I discussed forming an impenetrable Cyber Security unit so that election hacking, & many other negative things, will be guarded..",
		"...We negotiated a ceasefire in parts of Syria which will save lives. Now it is time to move forward in working constructively with Russia!",
		"I strongly pressed President Putin twice about Russian meddling in our election. He vehemently denied it. I've already given my opinion.....",
		"I look forward to all meetings today with world leaders, including my meeting with Vladimir Putin. Much to discuss. #G20Summit #USA",
		"Fake News CNN is looking at big management changes now that they got caught falsely pushing their phony Russian stories. Ratings way down!",
		"RT @foxandfriends: Hannity: Russia allegations 'boomeranging back' on Democrats https://t.co/lvdrpxpcp9",
		"Wow, CNN had to retract big story on Russia, with 3 employees forced to resign. What about all the other phony stories they do? FAKE NEWS!",
		"The real story is that President Obama did NOTHING after being informed in August about Russian meddling. With 4 months looking at Russia...",
		"The reason that President Obama did NOTHING about Russia after being notified by the CIA of meddling is that he expected Clinton would win..",
		"Obama Administration official said they choked when it came to acting on Russian meddling of election. They didn't want to hurt Hillary?",
		"Since the Obama Administration was told way before the 2016 Election that the Russians were meddling, why no action? Focus on them, not T!",
		"Just out: The Obama Administration knew far in advance of November 8th about election meddling by Russia. Did nothing about it. WHY?",
		"By the way, if Russia was working so hard on the 2016 Election, it all took place during the Obama Admin. Why didn't they stop them?",
		"Former Homeland Security Advisor Jeh Johnson is latest top intelligence official to state there was no grand scheme between Trump & Russia.",
		"RT @DiamondandSilk: The Media Says: The President Should Stop Tweeting about Russia. Well, Why Don't the Media Take Their Own Advice & S…",
		"After 7 months of investigations & committee hearings about my collusion with the Russians, nobody has been able to show any proof. Sad!",
		"Why is that Hillary Clintons family and Dems dealings with Russia are not looked at, but my non-dealings are?",
		"They made up a phony collusion with the Russians story, found zero proof, so now they go for obstruction of justice on the phony story. Nice",
		"RT @foxandfriends: Yesterday's hearings provided zero evidence of collusion between our campaign and the Russians because there wasn't any…",
		"So now it is reported that the Democrats, who have excoriated Carter Page about Russia, don't want him to testify. He blows away their....",
		"RT @foxandfriends: Jared Kushner didn't suggest Russian communications channel in meeting, source says https://t.co/nF6bM1FEt1",
		"Russian officials must be laughing at the U.S. & how a lame excuse for why the Dems lost the election has taken over the Fake News.",
		"...to terrorism and airline flight safety. Humanitarian reasons, plus I want Russia to greatly step up their fight against ISIS & terrorism.",
		"As President I wanted to share with Russia (at an openly scheduled W.H. meeting) which I have the absolute right to do, facts pertaining....",
		"Again, the story that there was collusion between the Russians & Trump campaign was fabricated by Dems as an excuse for losing the election.",
		"of Ukraine, Pavlo… https://t.co/hm4U54DCQO",
		"Russia must be laughing up their sleeves watching as the U.S. tears itself apart over a Democrat EXCUSE for losing the election.",
		"The Russia-Trump collusion story is a total hoax, when will this taxpayer funded charade end?",
		"Director Clapper reiterated what everybody, including the fake media already knows- there is no evidence of collusion w/ Russia and Trump.",
		"When will the Fake Media ask about the Dems dealings with Russia & why the DNC wouldn't allow the FBI to check their server or investigate?",
		"...Trump/Russia story was an excuse used by the Democrats as justification for losing the election. Perhaps Trump just ran a great campaign?",
		"RT @foxnation: . @TuckerCarlson : #Dems Don't Really Believe #Trump Is a Pawn of #Russia - That's Just Their Political Tool https://t.co/K…",
		"Things will work out fine between the U.S.A. and Russia. At the right time everyone will come to their senses & there will be lasting peace!",
		"Was the brother of John Podesta paid big money to get the sanctions on Russia lifted? Did Hillary know?",
		"..not associated with Russia. Trump team spied on before he was nominated. If this is true, does not get much bigger. Would be sad for U.S.",
		"It is the same Fake News Media that said there is no path to victory for Trump that is now pushing the phony Russia story. A total scam!",
		"When will Sleepy Eyes Chuck Todd and @NBCNews start talking about the Obama SURVEILLANCE SCANDAL and stop with the Fake Trump/Russia story?",
		"Why doesn't Fake News talk about Podesta ties to Russia as covered by @FoxNews or money from Russia to Clinton - sale of Uranium?",
		"Watch @foxandfriends now on Podesta and Russia!",
		"...money to Bill, the Hillary Russian reset, praise of Russia by Hillary, or Podesta Russian Company. Trump Russia story is a hoax. #MAGA!",
		"Why isn't the House Intelligence Committee looking into the Bill & Hillary deal that allowed big Uranium to go to Russia, Russian speech....",
		"Just watched the totally biased and fake news reports of the so-called Russia story on NBC and ABC. Such dishonesty!",
		"What about all of the contact with the Clinton campaign and the Russians? Also, is it true that the DNC would not let the FBI in to look?",
		"The Democrats made up and pushed the Russian story as an excuse for running a terrible campaign. Big advantage in Electoral College & lost!",
		"James Clapper and others stated that there is no evidence Potus colluded with Russia. This story is FAKE NEWS and everyone knows it!",
		"For eight years Russia ran over President Obama, got stronger and stronger, picked-off Crimea and added missiles. Weak! @foxandfriends",
		"Who was it that secretly said to Russian President, Tell Vladimir that after the election I'll have more flexibility? @foxandfriends",
		"Just out: The same Russian Ambassador that met Jeff Sessions visited the Obama White House 22 times, and 4 times last year alone.",
		"The first meeting Jeff Sessions had with the Russian Amb was set up by the Obama Administration under education program for 100 Ambs......",
		"I hereby demand a second investigation, after Schumer, of Pelosi for her close ties to Russia, and lying about it. https://t.co/qCDljfF3wN",
		"I hearby demand a second investigation, after Schumer, of Pelosi for her close ties to Russia, and lying about it. https://t.co/qCDljfF3wN",
		"I hear by demand a second investigation, after Schumer, of Pelosi for her close ties to Russia, and lying about it. https://t.co/qCDljfF3wN",
		"We should start an immediate investigation into @SenSchumer and his ties to Russia and Putin. A total hypocrite! https://t.co/Ik3yqjHzsA",
		"Russia talk is FAKE NEWS put out by the Dems, and played up by the media, in order to mask the big election defeat and the illegal leaks!",
		"The Democrats had to come up with a story as to why they lost the election, and so badly (306), so they made up a story - RUSSIA. Fake news!",
		"Crimea was TAKEN by Russia during the Obama Administration. Was Obama too soft on Russia?",
		"Information is being illegally given to the failing @nytimes & @washingtonpost by the intelligence community (NSA and FBI?).Just like Russia",
		"This Russian connection non-sense is merely an attempt to cover-up the many mistakes made in Hillary Clinton's losing campaign.",
		"I don't know Putin, have no deals in Russia, and the haters are going crazy - yet Obama can make a deal with Iran, #1 in terror, no problem!"
	]
end